apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: monitoring-poc
deploy:
  kubectl:
    manifests:
    - manifests/monitoring-poc-deployment.yaml
    - manifests/monitoring-poc-service-load-balancer.yaml